<?php

namespace Database\Seeders;

use App\Models\Property;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class PropertySeeder extends Seeder
{
    /**
     * Slug set explicitly per row below rather than relying on
     * Property::creating(). DatabaseSeeder wraps the whole run in
     * Model::withoutEvents() (via WithoutModelEvents), which also swallows
     * this seeder's model events since it runs inside that closure — the
     * slug-generation hook never fires, and slug is NOT NULL.
     */
    public function run(): void
    {
        $properties = [
            [
                'title' => 'Modern 4-Bedroom House in Nyambadwe',
                'description' => 'A spacious executive family home in one of Blantyre\'s most sought-after suburbs. Features an open-plan kitchen, fitted wardrobes throughout, a double garage, and a landscaped garden ideal for entertaining.',
                'category' => 'Residential',
                'type' => 'House',
                'price' => 185000000,
                'currency' => 'MWK',
                'location' => 'Nyambadwe, Blantyre',
                'status' => 'For Sale',
                'bedrooms' => 4,
                'bathrooms' => 3,
                'land_size' => '0.5 acres',
                'parking_spaces' => 2,
                'features' => ['Fitted kitchen', 'Borehole', 'Solar backup', 'Landscaped garden', 'Servant quarters'],
                'nearby_amenities' => ['Blantyre Sports Club', 'Chichiri Shopping Mall', 'St. Andrews International School'],
                'featured_image' => '',
                'is_featured' => true,
                'is_available' => true,
            ],
            [
                'title' => 'Contemporary 3-Bedroom Apartment, Area 47',
                'description' => 'Secure, gated apartment complex in Area 47 Sector 4, Lilongwe. Walking distance to Crossroads and Old Town shopping. Perfect for young professionals or a small family.',
                'category' => 'Residential',
                'type' => 'Apartment',
                'price' => 950000,
                'currency' => 'MWK',
                'location' => 'Area 47, Lilongwe',
                'status' => 'For Rent',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'land_size' => null,
                'parking_spaces' => 1,
                'features' => ['24hr security', 'Backup generator', 'Fitted wardrobes', 'Communal pool'],
                'nearby_amenities' => ['Crossroads Shopping Centre', 'Bishop Mackenzie International School'],
                'featured_image' => '',
                'is_featured' => true,
                'is_available' => true,
            ],
            [
                'title' => 'Prime Commercial Plot, Area 3 Lilongwe',
                'description' => 'A serviced commercial stand on a tarmac road in Lilongwe\'s Area 3 industrial belt. Suitable for warehousing, light manufacturing, or a retail development. Title deed available.',
                'category' => 'Commercial',
                'type' => 'Plot',
                'price' => 62000000,
                'currency' => 'MWK',
                'location' => 'Area 3, Lilongwe',
                'status' => 'For Sale',
                'bedrooms' => null,
                'bathrooms' => null,
                'land_size' => '1.2 acres',
                'parking_spaces' => null,
                'features' => ['Tarmac frontage', 'Serviced with water & power', 'Title deed', 'Fenced'],
                'nearby_amenities' => ['Kanengo Industrial Area', 'M1 Road access'],
                'featured_image' => '',
                'is_featured' => false,
                'is_available' => true,
            ],
            [
                'title' => 'Office Suite, City Centre Blantyre',
                'description' => 'Fully partitioned office suite on the 3rd floor of a well-maintained commercial building in Blantyre CBD. Includes reception area, boardroom, and dedicated parking bays.',
                'category' => 'Commercial',
                'type' => 'Office',
                'price' => 1400000,
                'currency' => 'MWK',
                'location' => 'City Centre, Blantyre',
                'status' => 'For Rent',
                'bedrooms' => null,
                'bathrooms' => 2,
                'land_size' => null,
                'parking_spaces' => 4,
                'features' => ['Fibre-ready', 'Backup generator', 'Lift access', 'Reception area'],
                'nearby_amenities' => ['Mandala', 'Standard Bank HQ', 'BT Supermarket'],
                'featured_image' => '',
                'is_featured' => true,
                'is_available' => true,
            ],
            [
                'title' => 'Residential Plot, Area 49',
                'description' => 'Undeveloped residential plot in the fast-growing Area 49 neighbourhood, Lilongwe. Level ground, ready for immediate construction, with an approved building plan on request.',
                'category' => 'Residential',
                'type' => 'Land',
                'price' => 28000000,
                'currency' => 'MWK',
                'location' => 'Area 49, Lilongwe',
                'status' => 'For Sale',
                'bedrooms' => null,
                'bathrooms' => null,
                'land_size' => '0.3 acres',
                'parking_spaces' => null,
                'features' => ['Level ground', 'Road access', 'Title deed'],
                'nearby_amenities' => ['Four Seasons', 'Parliament Building'],
                'featured_image' => '',
                'is_featured' => false,
                'is_available' => true,
            ],
            [
                'title' => 'Cosy 2-Bedroom House, Chilomoni',
                'description' => 'Affordable and well-maintained 2-bedroom house in Chilomoni, Blantyre. Fenced yard, reliable water supply, close to public transport routes into the CBD.',
                'category' => 'Residential',
                'type' => 'House',
                'price' => 45000000,
                'currency' => 'MWK',
                'location' => 'Chilomoni, Blantyre',
                'status' => 'For Sale',
                'bedrooms' => 2,
                'bathrooms' => 1,
                'land_size' => '0.15 acres',
                'parking_spaces' => 1,
                'features' => ['Fenced yard', 'Water tank', 'Fruit trees'],
                'nearby_amenities' => ['Chilomoni Market', 'Public transport stage'],
                'featured_image' => '',
                'is_featured' => false,
                'is_available' => true,
            ],
            [
                'title' => 'Luxury 5-Bedroom Villa, Area 43',
                'description' => 'An exceptional villa set on a manicured half-acre stand in Area 43, Lilongwe\'s diplomatic enclave. Swimming pool, staff quarters, and a home office wing.',
                'category' => 'Residential',
                'type' => 'House',
                'price' => 3200,
                'currency' => 'USD',
                'location' => 'Area 43, Lilongwe',
                'status' => 'For Rent',
                'bedrooms' => 5,
                'bathrooms' => 4,
                'land_size' => '0.5 acres',
                'parking_spaces' => 3,
                'features' => ['Swimming pool', 'Staff quarters', 'Home office', 'High wall & electric fence'],
                'nearby_amenities' => ['Diplomatic Enclave', 'Capital Hill', 'Sunbird Capital Hotel'],
                'featured_image' => '',
                'is_featured' => true,
                'is_available' => true,
            ],
            [
                'title' => 'Retail Shop Space, Limbe Market Area',
                'description' => 'Ground-floor retail unit in a busy trading strip near Limbe Market. High foot traffic, roller-shutter frontage, ideal for a general dealer or boutique.',
                'category' => 'Commercial',
                'type' => 'Commercial',
                'price' => 550000,
                'currency' => 'MWK',
                'location' => 'Limbe, Blantyre',
                'status' => 'For Rent',
                'bedrooms' => null,
                'bathrooms' => 1,
                'land_size' => null,
                'parking_spaces' => null,
                'features' => ['Roller shutter', 'High foot traffic', 'Storeroom'],
                'nearby_amenities' => ['Limbe Market', 'Limbe Railway Station'],
                'featured_image' => '',
                'is_featured' => false,
                'is_available' => true,
            ],
            [
                'title' => 'Agricultural Land, Salima Road',
                'description' => 'Ten acres of fertile farmland along the Salima road, suitable for horticulture or a weekend farm retreat. Borehole already sunk on site.',
                'category' => 'Residential',
                'type' => 'Land',
                'price' => 40000000,
                'currency' => 'MWK',
                'location' => 'Salima Road, Lilongwe',
                'status' => 'For Sale',
                'bedrooms' => null,
                'bathrooms' => null,
                'land_size' => '10 acres',
                'parking_spaces' => null,
                'features' => ['Borehole', 'Fertile soil', 'Road frontage'],
                'nearby_amenities' => ['Salima Turnoff', 'Lake Malawi (45 min drive)'],
                'featured_image' => '',
                'is_featured' => false,
                'is_available' => true,
            ],
            [
                'title' => 'Modern Townhouse, Sunnyside',
                'description' => 'A stylish 3-bedroom townhouse in a small gated cluster in Sunnyside, Blantyre. Low-maintenance living with shared communal gardens and 24-hour security.',
                'category' => 'Residential',
                'type' => 'House',
                'price' => 1750000,
                'currency' => 'MWK',
                'location' => 'Sunnyside, Blantyre',
                'status' => 'For Rent',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'land_size' => null,
                'parking_spaces' => 2,
                'features' => ['Gated cluster', '24hr security', 'Communal garden', 'Fitted kitchen'],
                'nearby_amenities' => ['Blantyre Girls Secondary', 'Sunnyside Shopping Centre'],
                'featured_image' => '',
                'is_featured' => false,
                'is_available' => true,
            ],
            [
                'title' => 'Warehouse Facility, Kanengo',
                'description' => 'A 1,500 sqm warehouse with adjoining office block in Kanengo Industrial Area, Lilongwe. High-clearance roof, three roller doors, and ample yard space for trucks.',
                'category' => 'Commercial',
                'type' => 'Commercial',
                'price' => 4500,
                'currency' => 'USD',
                'location' => 'Kanengo, Lilongwe',
                'status' => 'For Rent',
                'bedrooms' => null,
                'bathrooms' => 2,
                'land_size' => '2 acres',
                'parking_spaces' => 10,
                'features' => ['High-clearance roof', '3 roller doors', 'Truck yard', 'Office block'],
                'nearby_amenities' => ['Kanengo Industrial Area', 'M1 Road'],
                'featured_image' => '',
                'is_featured' => false,
                'is_available' => true,
            ],
            [
                'title' => 'Beachfront Plot, Senga Bay',
                'description' => 'A rare lakeshore plot at Senga Bay with direct beach access, perfect for a lodge or private holiday home development. Environmental clearance already obtained.',
                'category' => 'Residential',
                'type' => 'Plot',
                'price' => 15000,
                'currency' => 'USD',
                'location' => 'Senga Bay, Salima',
                'status' => 'For Sale',
                'bedrooms' => null,
                'bathrooms' => null,
                'land_size' => '0.8 acres',
                'parking_spaces' => null,
                'features' => ['Lake frontage', 'Environmental clearance', 'Title deed'],
                'nearby_amenities' => ['Senga Bay Resort', 'Lake Malawi'],
                'featured_image' => '',
                'is_featured' => true,
                'is_available' => true,
            ],
        ];

        foreach ($properties as $property) {
            $property['slug'] = Str::slug($property['title']);

            Property::updateOrCreate(
                ['title' => $property['title']],
                $property
            );
        }
    }
}
